### ISSUE TITLE
Recommend help language on annual income page

### ISSUE THREAD

**Issue by leannammiller** [department-of-veterans-affairs/healthcare-application#315]
https://github.com/department-of-veterans-affairs/healthcare-application-team/issues/465

**Comment by AnitraAppa** [comment]
@leannammiller Ah sorry I'm the worst - still owe you a response on this one. Real help to come today.

**Comment by AnitraAppa** [comment]
@leannammiller Actually, could I get a screenshot of where this help language would go? I was looking at the "Apply" page (https://www.vets.gov/healthcare/apply/) on another issue, but I think we're talking about a specific Annual Income page here. Is Sheila's help language for the form itself?

**Comment by leannammiller** [comment]
![screen shot 2016-12-16 at 12 31 33 pm](https://cloud.githubusercontent.com/assets/22749867/21272052/9bdb17d0-c38b-11e6-8d3a-f5db657154e2.png)

**Comment by leannammiller** [comment]
@AnitraAppa ^ is this helpful?

**Comment by AnitraAppa** [comment]
@leannammiller Ah right, Financial Disclosure page! Thanks, yes.

**Comment by AnitraAppa** [comment]
@leannammiller Oy sorry still wrapping up some HHS stuff today -- is it alright if I do this on Monday? I can definitely do it this weekend if we need it ASAP.

**Comment by leannammiller** [comment]
No problem @AnitraAppa

**Comment by AnitraAppa** [comment]
@leannammiller  - Thanks! I was confused earlier because I thought the request was to add this spouse income help information to the general Financial Disclosure page and I couldn't access to staging to get to the specific [Annual Income pag](https://www.vets.gov/healthcare/apply/application/household-information/annual-income)e a few steps further into Household Information. Got the prod link now though: https://www.vets.gov/healthcare/apply/application/household-information/annual-income

1. Recommending adding this to the end of the help content on "Annual Income" page, above the first field:
"For more information about what income sources to include, [check this reference guide](http://www.va.gov/healthbenefits/resources/publications/IB10-454_quick_reference_guide_income_and_assets.pdf) [link arrow]."

2. Recommend adding the estranged deductible info to the page after this, the "[Deductible Expenses](https://www.vets.gov/healthcare/apply/application/household-information/deductible-expenses)" page. I believe this is where that info applies, but shout if I'm wrong here:
"**If you are separated but still providing support to your spouse**: Include your spouse’s income and deductible expenses. If you provide child support, don't count the child support as a deductible expense."

Note: Need to check if "estranged" is the official word here or if I should use "separated", "divorced", "former spouse" etc. 

3. I'm not sure if I fully understand what the Veteran needs to do in the remaining scenarios below -- from Sheila's notes:
"Your spouse’s income and deductible expenses will be prorated for the months you were married or your marriage was intact. If a court order awarded your ex-spouse a portion of your military or civil service retirement, this will be deducted from your income."

@leannammiller @akainic 
- To confirm, does the VA calculate this for them? I don't see fields to make these distinctions, so want to make sure if the Veteran needs to do this prorating or deduction they have that info. Feel free to Slack or call tomorrow if it's easier to talk through this live.
- Does there happen to be another cheat sheet for estranged or divorced spouse situation that I could link into? Suspect there may be other scenarios there and would like to link out instead of making the main flow longer for all cases. But if there isn't and these are the main points that Sheila thinks it's worth nothing, can take a stab at including these into the main flow.

**Comment by AnitraAppa** [comment]
@leannammiller any update on this one? Had a few questions in the comment above.

**Comment by leannammiller** [comment]
Thanks for reminder - I'll add this to my list and review.
