### ISSUE TITLE
Use healthcheck to display message if down

### ISSUE THREAD

**Issue by leannammiller** [department-of-veterans-affairs/healthcare-application#317]
see https://github.com/department-of-veterans-affairs/healthcare-application-team/issues/307

to discuss 12/19

**Comment by leannammiller** [comment]
@annekainicUSDS = should we discuss?

**Comment by J-Quag** [comment]
@annekainicUSDS  @markolson   Do we still need this? DevOps handles monitoring. Would like to close this if its no longer needed.

**Comment by J-Quag** [comment]
@markolson  do you know what this is / is this still a thing?

**Comment by annekainicUSDS** [comment]
@J-Quag Devops handles monitoring, but nothing is displayed to the user if a service is down. The purpose of this ticket is to use the monitoring to then tell the user when the service is down so they don't unnecessarily fill out the form. We started conversations around this and it became complicated as to when we should alert them to this issue: before they start filling out the form? At any point during filling out the form? Right before submitting? I think this problem changes once we have save progress because the risk of the user losing their work goes away. Since save progress is on the horizon, I say we table this until then and revisit once we have save progress.

**Comment by J-Quag** [comment]
Opening new tickets in vets-team repo. Closing this one as HCA repo no longer exists.
