### ISSUE TITLE
Feature Request: Provide more helpful error message

### ISSUE THREAD

**Issue by leannammiller** [department-of-veterans-affairs/healthcare-application#320]
see: https://github.com/department-of-veterans-affairs/healthcare-application-team/issues/432

**Comment by AnitraAppa** [comment]
@leannammiller - From Anne's comment on department-of-veterans-affairs/healthcare-application-team#432, it sounds like we've fixed this error, but want to create better messaging for other errors that could come up and cause a failed submission.
- What are the other errors still hanging around?
- Is it possible to show them  in-line before the user has clicked submit?

**Comment by AnitraAppa** [comment]
@akainic or @leannammiller - Let me know if you know which errors we need to create messaging for or if we're still figuring that out

**Comment by akainic** [comment]
@AnitraAppa @leannammiller I think this ticket is more of a back-end issue at this point. The problem is that we need to be able to translate the error code we get back from the failed submission into something useful for the user so they can correct whatever it is that caused the submission to fail. Right now we don't have the ability to do this, so we would need to implement something that would provide more specific error messaging to the front-end. Sorry for the confusion @AnitraAppa!

**Comment by AnitraAppa** [comment]
@akainic Gotcha, that makes sense! Happy to help when it looks like we have the ability to translate those error codes.

**Comment by J-Quag** [comment]
@markolson  @lihanli   What do we need to actually implement this?

**Comment by lihanli** [comment]
@J-Quag currently the backend is relaying the submission error message in the response so maybe this is resolved?

**Comment by J-Quag** [comment]
@markolson ?
