### ISSUE TITLE
More informative SSN feedback

### ISSUE THREAD

**Issue by leannammiller** [department-of-veterans-affairs/healthcare-application#327]
see https://github.com/department-of-veterans-affairs/healthcare-application-team/issues/192

**Comment by annekainicUSDS** [comment]
I think the purpose of this ticket was to provide more detailed error messages if the SSN is not valid. There are multiple reason the SSN would be invalid: too few or too many numbers, invalid characters, invalid combination of characters (i.e., `111-22-3333`). Create more specific error messages that would tie to these scenarios. 

I think this is a very low priority thing to do.

**Comment by J-Quag** [comment]
usability tests, validation errors due to 9 digit number and dashes okay, not working for folks. 
Should have a more helpful error message. 
Issue with people entering sequential numbers
Any way to track which fields get errors and failed validation. Could do that. -GA/also how do we get the data from our system to send it at the right time. 
Looking at this in another ticket for more general look at doing validation error tracking.
